// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tx/pse/v1/distribution.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ClearingAccountMapping defines the mapping between a clearing account (module account) and its recipients (sub account multisig wallets).
// This mapping can be modified via governance proposals.
// Each clearing account must have at least one recipient address.
// During distribution, the allocated amount is split equally among all recipients.
type ClearingAccountMapping struct {
	// clearing_account is the name of the clearing account holding the tokens to be distributed.
	ClearingAccount string `protobuf:"bytes,1,opt,name=clearing_account,json=clearingAccount,proto3" json:"clearing_account,omitempty" yaml:"clearing_account"`
	// recipient_addresses is the list of multisig wallet addresses that will receive the token distributions.
	// Must have at least one address. Distribution amount is split equally among all recipients.
	RecipientAddresses []string `protobuf:"bytes,2,rep,name=recipient_addresses,json=recipientAddresses,proto3" json:"recipient_addresses,omitempty" yaml:"recipient_addresses"`
}

func (m *ClearingAccountMapping) Reset()         { *m = ClearingAccountMapping{} }
func (m *ClearingAccountMapping) String() string { return proto.CompactTextString(m) }
func (*ClearingAccountMapping) ProtoMessage()    {}
func (*ClearingAccountMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_a549fe743b42ab69, []int{0}
}
func (m *ClearingAccountMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClearingAccountMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClearingAccountMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClearingAccountMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearingAccountMapping.Merge(m, src)
}
func (m *ClearingAccountMapping) XXX_Size() int {
	return m.Size()
}
func (m *ClearingAccountMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearingAccountMapping.DiscardUnknown(m)
}

var xxx_messageInfo_ClearingAccountMapping proto.InternalMessageInfo

func (m *ClearingAccountMapping) GetClearingAccount() string {
	if m != nil {
		return m.ClearingAccount
	}
	return ""
}

func (m *ClearingAccountMapping) GetRecipientAddresses() []string {
	if m != nil {
		return m.RecipientAddresses
	}
	return nil
}

// ClearingAccountAllocation defines the amount to be allocated from a specific clearing account (module account).
type ClearingAccountAllocation struct {
	// clearing_account is the name of the clearing account (module account).
	ClearingAccount string `protobuf:"bytes,1,opt,name=clearing_account,json=clearingAccount,proto3" json:"clearing_account,omitempty" yaml:"clearing_account"`
	// amount is the number of tokens to allocate from this clearing account.
	// This amount is for the allocation denom (see AllocationDenom constant).
	Amount cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount" yaml:"amount"`
}

func (m *ClearingAccountAllocation) Reset()         { *m = ClearingAccountAllocation{} }
func (m *ClearingAccountAllocation) String() string { return proto.CompactTextString(m) }
func (*ClearingAccountAllocation) ProtoMessage()    {}
func (*ClearingAccountAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_a549fe743b42ab69, []int{1}
}
func (m *ClearingAccountAllocation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClearingAccountAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClearingAccountAllocation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClearingAccountAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearingAccountAllocation.Merge(m, src)
}
func (m *ClearingAccountAllocation) XXX_Size() int {
	return m.Size()
}
func (m *ClearingAccountAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearingAccountAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_ClearingAccountAllocation proto.InternalMessageInfo

func (m *ClearingAccountAllocation) GetClearingAccount() string {
	if m != nil {
		return m.ClearingAccount
	}
	return ""
}

// ScheduledDistribution defines a single allocation event at a specific timestamp.
// Multiple clearing accounts can allocate tokens at the same time.
// Each distribution is identified by a unique, sequential id.
type ScheduledDistribution struct {
	// timestamp is when this allocation should occur (Unix timestamp in seconds).
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty" yaml:"timestamp"`
	// allocations is the list of amounts to allocate from each clearing account at this time.
	Allocations []ClearingAccountAllocation `protobuf:"bytes,2,rep,name=allocations,proto3" json:"allocations" yaml:"allocations"`
	// id is the unique, sequential identifier for this distribution.
	// Used as the storage key in the AllocationSchedule map.
	ID uint64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty" yaml:"id"`
}

func (m *ScheduledDistribution) Reset()         { *m = ScheduledDistribution{} }
func (m *ScheduledDistribution) String() string { return proto.CompactTextString(m) }
func (*ScheduledDistribution) ProtoMessage()    {}
func (*ScheduledDistribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_a549fe743b42ab69, []int{2}
}
func (m *ScheduledDistribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ScheduledDistribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ScheduledDistribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ScheduledDistribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduledDistribution.Merge(m, src)
}
func (m *ScheduledDistribution) XXX_Size() int {
	return m.Size()
}
func (m *ScheduledDistribution) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduledDistribution.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduledDistribution proto.InternalMessageInfo

func (m *ScheduledDistribution) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ScheduledDistribution) GetAllocations() []ClearingAccountAllocation {
	if m != nil {
		return m.Allocations
	}
	return nil
}

func (m *ScheduledDistribution) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterType((*ClearingAccountMapping)(nil), "tx.pse.v1.ClearingAccountMapping")
	proto.RegisterType((*ClearingAccountAllocation)(nil), "tx.pse.v1.ClearingAccountAllocation")
	proto.RegisterType((*ScheduledDistribution)(nil), "tx.pse.v1.ScheduledDistribution")
}

func init() { proto.RegisterFile("tx/pse/v1/distribution.proto", fileDescriptor_a549fe743b42ab69) }

var fileDescriptor_a549fe743b42ab69 = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x6a, 0xd4, 0x40,
	0x18, 0xc7, 0x37, 0xa9, 0x14, 0x32, 0x45, 0x2c, 0xe9, 0x56, 0xb7, 0xab, 0x64, 0x4a, 0xf4, 0xd0,
	0xcb, 0x66, 0x68, 0x05, 0x05, 0xf1, 0xb2, 0xb1, 0x28, 0x7b, 0xf0, 0x92, 0x7a, 0xf2, 0xb2, 0xcc,
	0xce, 0x0c, 0xd9, 0xa1, 0xc9, 0x4c, 0xc8, 0xcc, 0x2e, 0x5b, 0x9f, 0xc2, 0x87, 0xf1, 0xe2, 0x1b,
	0xd4, 0x5b, 0x11, 0x0f, 0xe2, 0x61, 0x90, 0xdd, 0x37, 0xc8, 0x13, 0x48, 0x32, 0x21, 0xad, 0x45,
	0x6f, 0xbd, 0x25, 0xdf, 0xf7, 0xff, 0x7e, 0xfc, 0xff, 0xdf, 0x7c, 0xe0, 0x89, 0x5e, 0xa1, 0x42,
	0x31, 0xb4, 0x3c, 0x46, 0x94, 0x2b, 0x5d, 0xf2, 0xd9, 0x42, 0x73, 0x29, 0xa2, 0xa2, 0x94, 0x5a,
	0xfa, 0x9e, 0x5e, 0x45, 0x85, 0x62, 0xd1, 0xf2, 0x78, 0x78, 0x40, 0xa4, 0xca, 0xa5, 0x9a, 0x36,
	0x0d, 0x64, 0x7f, 0xac, 0x6a, 0xd8, 0x4f, 0x65, 0x2a, 0x6d, 0xbd, 0xfe, 0xb2, 0xd5, 0xf0, 0x9b,
	0x03, 0x1e, 0xbe, 0xc9, 0x18, 0x2e, 0xb9, 0x48, 0xc7, 0x84, 0xc8, 0x85, 0xd0, 0xef, 0x71, 0x51,
	0x70, 0x91, 0xfa, 0x6f, 0xc1, 0x2e, 0x69, 0x3b, 0x53, 0x6c, 0x5b, 0x03, 0xe7, 0xd0, 0x39, 0xf2,
	0xe2, 0xc7, 0x95, 0x81, 0x8f, 0x2e, 0x70, 0x9e, 0xbd, 0x0a, 0x6f, 0x2b, 0xc2, 0xe4, 0x01, 0xf9,
	0x1b, 0xe7, 0xa7, 0x60, 0xaf, 0x64, 0x84, 0x17, 0x9c, 0x09, 0x3d, 0xc5, 0x94, 0x96, 0x4c, 0x29,
	0xa6, 0x06, 0xee, 0xe1, 0xd6, 0x91, 0x17, 0xbf, 0xa8, 0x0c, 0x1c, 0x5a, 0xd4, 0x3f, 0x44, 0xe1,
	0xf7, 0x2f, 0xa3, 0x7e, 0x9b, 0x62, 0x6c, 0x8b, 0x67, 0xba, 0x66, 0x27, 0x7e, 0xa7, 0x1e, 0x77,
	0xe2, 0xaf, 0x0e, 0x38, 0xb8, 0x95, 0x65, 0x9c, 0x65, 0x92, 0xe0, 0x7a, 0x57, 0x77, 0x16, 0xe7,
	0x03, 0xd8, 0xc6, 0x79, 0x33, 0xed, 0x36, 0xd3, 0xaf, 0x2f, 0x0d, 0xec, 0xfd, 0x32, 0x70, 0xdf,
	0xfa, 0x54, 0xf4, 0x3c, 0xe2, 0x12, 0xe5, 0x58, 0xcf, 0xa3, 0x89, 0xd0, 0x95, 0x81, 0xf7, 0x2d,
	0xda, 0x0e, 0xd5, 0x89, 0x40, 0x9b, 0x68, 0x22, 0x74, 0xd2, 0xb2, 0xc2, 0x1f, 0x0e, 0xd8, 0x3f,
	0x23, 0x73, 0x46, 0x17, 0x19, 0xa3, 0xa7, 0x37, 0xde, 0xd8, 0x3f, 0x01, 0x9e, 0xe6, 0x39, 0x53,
	0x1a, 0xe7, 0x45, 0x63, 0xf8, 0x5e, 0xdc, 0xaf, 0x0c, 0xdc, 0xb5, 0xd4, 0xae, 0x15, 0x26, 0xd7,
	0x32, 0x7f, 0x06, 0x76, 0x70, 0x97, 0xdc, 0xae, 0x7a, 0xe7, 0xe4, 0x59, 0xd4, 0xdd, 0x49, 0xf4,
	0xdf, 0x35, 0xc5, 0xc3, 0x3a, 0x4e, 0x65, 0xa0, 0xdf, 0xba, 0xbe, 0xc6, 0x84, 0xc9, 0x4d, 0xa8,
	0xff, 0x14, 0xb8, 0x9c, 0x0e, 0xb6, 0x1a, 0x43, 0x7b, 0x6b, 0x03, 0xdd, 0xc9, 0x69, 0x65, 0xa0,
	0x67, 0xc7, 0x38, 0x0d, 0x13, 0x97, 0xd3, 0xf8, 0xdd, 0xe5, 0x3a, 0x70, 0xae, 0xd6, 0x81, 0xf3,
	0x7b, 0x1d, 0x38, 0x9f, 0x37, 0x41, 0xef, 0x6a, 0x13, 0xf4, 0x7e, 0x6e, 0x82, 0xde, 0xc7, 0x51,
	0xca, 0xf5, 0x7c, 0x31, 0x8b, 0x88, 0xcc, 0x91, 0x96, 0xe7, 0x4c, 0xf0, 0x4f, 0x6c, 0xb4, 0x42,
	0x7a, 0x35, 0x22, 0x73, 0xcc, 0x05, 0x5a, 0xbe, 0x44, 0xf6, 0xe6, 0xf5, 0x45, 0xc1, 0xd4, 0x6c,
	0xbb, 0x39, 0xd7, 0xe7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x61, 0xb5, 0xdc, 0x1b, 0x0a, 0x03,
	0x00, 0x00,
}

func (m *ClearingAccountMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClearingAccountMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClearingAccountMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RecipientAddresses) > 0 {
		for iNdEx := len(m.RecipientAddresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RecipientAddresses[iNdEx])
			copy(dAtA[i:], m.RecipientAddresses[iNdEx])
			i = encodeVarintDistribution(dAtA, i, uint64(len(m.RecipientAddresses[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ClearingAccount) > 0 {
		i -= len(m.ClearingAccount)
		copy(dAtA[i:], m.ClearingAccount)
		i = encodeVarintDistribution(dAtA, i, uint64(len(m.ClearingAccount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ClearingAccountAllocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClearingAccountAllocation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClearingAccountAllocation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintDistribution(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ClearingAccount) > 0 {
		i -= len(m.ClearingAccount)
		copy(dAtA[i:], m.ClearingAccount)
		i = encodeVarintDistribution(dAtA, i, uint64(len(m.ClearingAccount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ScheduledDistribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScheduledDistribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScheduledDistribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ID != 0 {
		i = encodeVarintDistribution(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Allocations) > 0 {
		for iNdEx := len(m.Allocations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Allocations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDistribution(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Timestamp != 0 {
		i = encodeVarintDistribution(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintDistribution(dAtA []byte, offset int, v uint64) int {
	offset -= sovDistribution(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ClearingAccountMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClearingAccount)
	if l > 0 {
		n += 1 + l + sovDistribution(uint64(l))
	}
	if len(m.RecipientAddresses) > 0 {
		for _, s := range m.RecipientAddresses {
			l = len(s)
			n += 1 + l + sovDistribution(uint64(l))
		}
	}
	return n
}

func (m *ClearingAccountAllocation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClearingAccount)
	if l > 0 {
		n += 1 + l + sovDistribution(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovDistribution(uint64(l))
	return n
}

func (m *ScheduledDistribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Timestamp != 0 {
		n += 1 + sovDistribution(uint64(m.Timestamp))
	}
	if len(m.Allocations) > 0 {
		for _, e := range m.Allocations {
			l = e.Size()
			n += 1 + l + sovDistribution(uint64(l))
		}
	}
	if m.ID != 0 {
		n += 1 + sovDistribution(uint64(m.ID))
	}
	return n
}

func sovDistribution(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDistribution(x uint64) (n int) {
	return sovDistribution(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClearingAccountMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDistribution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClearingAccountMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClearingAccountMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClearingAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClearingAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecipientAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecipientAddresses = append(m.RecipientAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDistribution(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDistribution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClearingAccountAllocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDistribution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClearingAccountAllocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClearingAccountAllocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClearingAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClearingAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDistribution(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDistribution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ScheduledDistribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDistribution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ScheduledDistribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ScheduledDistribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Allocations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDistribution
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDistribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Allocations = append(m.Allocations, ClearingAccountAllocation{})
			if err := m.Allocations[len(m.Allocations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDistribution(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDistribution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDistribution(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDistribution
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDistribution
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDistribution
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDistribution
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDistribution
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDistribution
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDistribution        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDistribution          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDistribution = fmt.Errorf("proto: unexpected end of group")
)
