// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tx/pse/v1/event.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventDistributionCompleted is emitted when a periodic distribution is successfully completed.
type EventDistributionCompleted struct {
	// module_account is the source module account name from which tokens are distributed.
	ModuleAccount string `protobuf:"bytes,1,opt,name=module_account,json=moduleAccount,proto3" json:"module_account,omitempty"`
	// sub_account is the destination sub-account receiving the tokens.
	SubAccount string `protobuf:"bytes,2,opt,name=sub_account,json=subAccount,proto3" json:"sub_account,omitempty"`
	// scheduled_time is the Unix timestamp when the distribution was scheduled to occur.
	ScheduledTime uint64 `protobuf:"varint,3,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	// actual_time is the Unix timestamp when the distribution actually occurred.
	ActualTime uint64 `protobuf:"varint,4,opt,name=actual_time,json=actualTime,proto3" json:"actual_time,omitempty"`
	// amount is the amount of tokens distributed.
	Amount cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
	// denom is the denomination of the tokens distributed.
	Denom string `protobuf:"bytes,6,opt,name=denom,proto3" json:"denom,omitempty"`
	// block_height is the block height at which the distribution occurred.
	BlockHeight int64 `protobuf:"varint,7,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *EventDistributionCompleted) Reset()         { *m = EventDistributionCompleted{} }
func (m *EventDistributionCompleted) String() string { return proto.CompactTextString(m) }
func (*EventDistributionCompleted) ProtoMessage()    {}
func (*EventDistributionCompleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_01c86a7bc3b1fadd, []int{0}
}
func (m *EventDistributionCompleted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventDistributionCompleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventDistributionCompleted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventDistributionCompleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventDistributionCompleted.Merge(m, src)
}
func (m *EventDistributionCompleted) XXX_Size() int {
	return m.Size()
}
func (m *EventDistributionCompleted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventDistributionCompleted.DiscardUnknown(m)
}

var xxx_messageInfo_EventDistributionCompleted proto.InternalMessageInfo

func (m *EventDistributionCompleted) GetModuleAccount() string {
	if m != nil {
		return m.ModuleAccount
	}
	return ""
}

func (m *EventDistributionCompleted) GetSubAccount() string {
	if m != nil {
		return m.SubAccount
	}
	return ""
}

func (m *EventDistributionCompleted) GetScheduledTime() uint64 {
	if m != nil {
		return m.ScheduledTime
	}
	return 0
}

func (m *EventDistributionCompleted) GetActualTime() uint64 {
	if m != nil {
		return m.ActualTime
	}
	return 0
}

func (m *EventDistributionCompleted) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *EventDistributionCompleted) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*EventDistributionCompleted)(nil), "tx.pse.v1.EventDistributionCompleted")
}

func init() { proto.RegisterFile("tx/pse/v1/event.proto", fileDescriptor_01c86a7bc3b1fadd) }

var fileDescriptor_01c86a7bc3b1fadd = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0xcf, 0x6a, 0xea, 0x40,
	0x14, 0xc6, 0x13, 0xff, 0x5d, 0x1c, 0xaf, 0x2e, 0x82, 0x42, 0x10, 0x6e, 0xf4, 0x5e, 0x10, 0xdc,
	0x98, 0x41, 0x2e, 0xed, 0xbe, 0xb6, 0xa5, 0xed, 0x36, 0x74, 0xd5, 0x8d, 0x24, 0x93, 0x21, 0x19,
	0xcc, 0xe4, 0x04, 0xe7, 0x24, 0xa4, 0x7d, 0x8a, 0x3e, 0x40, 0x1f, 0xc8, 0xa5, 0xcb, 0xd2, 0x85,
	0x14, 0x7d, 0x91, 0x92, 0x49, 0xeb, 0x6e, 0xe6, 0xc7, 0xef, 0x9b, 0x6f, 0x38, 0x87, 0x8c, 0xb0,
	0xa4, 0x99, 0xe2, 0xb4, 0x58, 0x52, 0x5e, 0xf0, 0x14, 0xdd, 0x6c, 0x0b, 0x08, 0x56, 0x17, 0x4b,
	0x37, 0x53, 0xdc, 0x2d, 0x96, 0xe3, 0x61, 0x04, 0x11, 0x68, 0x4a, 0xab, 0x53, 0x2d, 0xfc, 0x7b,
	0x6b, 0x90, 0xf1, 0x6d, 0x15, 0xb8, 0x11, 0x0a, 0xb7, 0x22, 0xc8, 0x51, 0x40, 0x7a, 0x0d, 0x32,
	0x4b, 0x38, 0xf2, 0xd0, 0x9a, 0x91, 0x81, 0x84, 0x30, 0x4f, 0xf8, 0xda, 0x67, 0x0c, 0xf2, 0x14,
	0x6d, 0x73, 0x6a, 0xce, 0xbb, 0x5e, 0xbf, 0xa6, 0x57, 0x35, 0xb4, 0x26, 0xa4, 0xa7, 0xf2, 0xe0,
	0xec, 0x34, 0xb4, 0x43, 0x54, 0x1e, 0xfc, 0x08, 0x33, 0x32, 0x50, 0x2c, 0xe6, 0x55, 0x26, 0x5c,
	0xa3, 0x90, 0xdc, 0x6e, 0x4e, 0xcd, 0x79, 0xcb, 0xeb, 0x9f, 0xe9, 0xa3, 0x90, 0xbc, 0x7a, 0xc7,
	0x67, 0x98, 0xfb, 0x49, 0xed, 0xb4, 0xb4, 0x43, 0x6a, 0xa4, 0x85, 0x0b, 0xd2, 0xf1, 0xa5, 0xee,
	0x68, 0x57, 0x1d, 0xab, 0x3f, 0xbb, 0xc3, 0xc4, 0xf8, 0x38, 0x4c, 0x46, 0x0c, 0x94, 0x04, 0xa5,
	0xc2, 0x8d, 0x2b, 0x80, 0x4a, 0x1f, 0x63, 0xf7, 0x21, 0x45, 0xef, 0x5b, 0xb6, 0x86, 0xa4, 0x1d,
	0xf2, 0x14, 0xa4, 0xdd, 0xd1, 0x3f, 0xab, 0x2f, 0xd6, 0x5f, 0xf2, 0x3b, 0x48, 0x80, 0x6d, 0xd6,
	0x31, 0x17, 0x51, 0x8c, 0xf6, 0xaf, 0xa9, 0x39, 0x6f, 0x7a, 0x3d, 0xcd, 0xee, 0x35, 0x5a, 0xdd,
	0xed, 0x8e, 0x8e, 0xb9, 0x3f, 0x3a, 0xe6, 0xe7, 0xd1, 0x31, 0x5f, 0x4f, 0x8e, 0xb1, 0x3f, 0x39,
	0xc6, 0xfb, 0xc9, 0x31, 0x9e, 0x16, 0x91, 0xc0, 0x38, 0x0f, 0x5c, 0x06, 0x92, 0x22, 0x6c, 0x78,
	0x2a, 0x5e, 0xf8, 0xa2, 0xa4, 0x58, 0x2e, 0x58, 0xec, 0x8b, 0x94, 0x16, 0x97, 0xb4, 0xde, 0x08,
	0x3e, 0x67, 0x5c, 0x05, 0x1d, 0x3d, 0xee, 0xff, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x38,
	0x83, 0x50, 0xa8, 0x01, 0x00, 0x00,
}

func (m *EventDistributionCompleted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventDistributionCompleted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventDistributionCompleted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x32
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.ActualTime != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ActualTime))
		i--
		dAtA[i] = 0x20
	}
	if m.ScheduledTime != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ScheduledTime))
		i--
		dAtA[i] = 0x18
	}
	if len(m.SubAccount) > 0 {
		i -= len(m.SubAccount)
		copy(dAtA[i:], m.SubAccount)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.SubAccount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ModuleAccount) > 0 {
		i -= len(m.ModuleAccount)
		copy(dAtA[i:], m.ModuleAccount)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.ModuleAccount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventDistributionCompleted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ModuleAccount)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.SubAccount)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.ScheduledTime != 0 {
		n += 1 + sovEvent(uint64(m.ScheduledTime))
	}
	if m.ActualTime != 0 {
		n += 1 + sovEvent(uint64(m.ActualTime))
	}
	l = m.Amount.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovEvent(uint64(m.BlockHeight))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventDistributionCompleted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventDistributionCompleted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventDistributionCompleted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModuleAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScheduledTime", wireType)
			}
			m.ScheduledTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ScheduledTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActualTime", wireType)
			}
			m.ActualTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActualTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
