// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tx/pse/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the module's genesis state.
type GenesisState struct {
	// params contains all gov-manageable parameters.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// scheduled_distributions contains all scheduled distributions (both past and pending).
	// Stored as a list for genesis import/export, but will be stored as a map in state.
	// Must be sorted by timestamp in ascending order.
	// Completed allocations are removed from the map after processing.
	ScheduledDistributions []ScheduledDistribution     `protobuf:"bytes,2,rep,name=scheduled_distributions,json=scheduledDistributions,proto3" json:"scheduled_distributions" yaml:"scheduled_distributions"`
	DelegationTimeEntries  []DelegationTimeEntryExport `protobuf:"bytes,3,rep,name=delegation_time_entries,json=delegationTimeEntries,proto3" json:"delegation_time_entries" yaml:"delegation_time_entries"`
	AccountScores          []AccountScore              `protobuf:"bytes,4,rep,name=account_scores,json=accountScores,proto3" json:"account_scores" yaml:"account_scores"`
	DistributionsDisabled  bool                        `protobuf:"varint,5,opt,name=distributions_disabled,json=distributionsDisabled,proto3" json:"distributions_disabled,omitempty" yaml:"distributions_disabled"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d215b1db402695da, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetScheduledDistributions() []ScheduledDistribution {
	if m != nil {
		return m.ScheduledDistributions
	}
	return nil
}

func (m *GenesisState) GetDelegationTimeEntries() []DelegationTimeEntryExport {
	if m != nil {
		return m.DelegationTimeEntries
	}
	return nil
}

func (m *GenesisState) GetAccountScores() []AccountScore {
	if m != nil {
		return m.AccountScores
	}
	return nil
}

func (m *GenesisState) GetDistributionsDisabled() bool {
	if m != nil {
		return m.DistributionsDisabled
	}
	return false
}

type DelegationTimeEntryExport struct {
	ValidatorAddress   string                      `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty" yaml:"validator_address"`
	DelegatorAddress   string                      `protobuf:"bytes,2,opt,name=delegator_address,json=delegatorAddress,proto3" json:"delegator_address,omitempty" yaml:"delegator_address"`
	Shares             cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=shares,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"shares" yaml:"shares"`
	LastChangedUnixSec int64                       `protobuf:"varint,4,opt,name=last_changed_unix_sec,json=lastChangedUnixSec,proto3" json:"last_changed_unix_sec,omitempty" yaml:"last_changed_unix_sec"`
	DistributionID     uint64                      `protobuf:"varint,5,opt,name=distribution_id,json=distributionId,proto3" json:"distribution_id,omitempty" yaml:"distribution_id"`
}

func (m *DelegationTimeEntryExport) Reset()         { *m = DelegationTimeEntryExport{} }
func (m *DelegationTimeEntryExport) String() string { return proto.CompactTextString(m) }
func (*DelegationTimeEntryExport) ProtoMessage()    {}
func (*DelegationTimeEntryExport) Descriptor() ([]byte, []int) {
	return fileDescriptor_d215b1db402695da, []int{1}
}
func (m *DelegationTimeEntryExport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegationTimeEntryExport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegationTimeEntryExport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegationTimeEntryExport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegationTimeEntryExport.Merge(m, src)
}
func (m *DelegationTimeEntryExport) XXX_Size() int {
	return m.Size()
}
func (m *DelegationTimeEntryExport) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegationTimeEntryExport.DiscardUnknown(m)
}

var xxx_messageInfo_DelegationTimeEntryExport proto.InternalMessageInfo

func (m *DelegationTimeEntryExport) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *DelegationTimeEntryExport) GetDelegatorAddress() string {
	if m != nil {
		return m.DelegatorAddress
	}
	return ""
}

func (m *DelegationTimeEntryExport) GetLastChangedUnixSec() int64 {
	if m != nil {
		return m.LastChangedUnixSec
	}
	return 0
}

func (m *DelegationTimeEntryExport) GetDistributionID() uint64 {
	if m != nil {
		return m.DistributionID
	}
	return 0
}

type AccountScore struct {
	Address        string                `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" yaml:"address"`
	Score          cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=score,proto3,customtype=cosmossdk.io/math.Int" json:"score" yaml:"score"`
	DistributionID uint64                `protobuf:"varint,3,opt,name=distribution_id,json=distributionId,proto3" json:"distribution_id,omitempty" yaml:"distribution_id"`
}

func (m *AccountScore) Reset()         { *m = AccountScore{} }
func (m *AccountScore) String() string { return proto.CompactTextString(m) }
func (*AccountScore) ProtoMessage()    {}
func (*AccountScore) Descriptor() ([]byte, []int) {
	return fileDescriptor_d215b1db402695da, []int{2}
}
func (m *AccountScore) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountScore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountScore.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountScore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountScore.Merge(m, src)
}
func (m *AccountScore) XXX_Size() int {
	return m.Size()
}
func (m *AccountScore) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountScore.DiscardUnknown(m)
}

var xxx_messageInfo_AccountScore proto.InternalMessageInfo

func (m *AccountScore) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AccountScore) GetDistributionID() uint64 {
	if m != nil {
		return m.DistributionID
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "tx.pse.v1.GenesisState")
	proto.RegisterType((*DelegationTimeEntryExport)(nil), "tx.pse.v1.DelegationTimeEntryExport")
	proto.RegisterType((*AccountScore)(nil), "tx.pse.v1.AccountScore")
}

func init() { proto.RegisterFile("tx/pse/v1/genesis.proto", fileDescriptor_d215b1db402695da) }

var fileDescriptor_d215b1db402695da = []byte{
	// 703 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x8d, 0x9b, 0xb4, 0xdf, 0xd7, 0x69, 0x9b, 0xef, 0xab, 0xd5, 0xfc, 0xb4, 0xb4, 0x71, 0xb0,
	0x10, 0x8a, 0x10, 0xb1, 0xd5, 0x82, 0x84, 0x04, 0xab, 0x9a, 0x54, 0x55, 0x24, 0x16, 0xe0, 0x50,
	0x09, 0x55, 0x42, 0xd6, 0xc4, 0x1e, 0x39, 0xa3, 0xc6, 0x9e, 0xc8, 0x33, 0x89, 0x1c, 0x76, 0x08,
	0x1e, 0x80, 0x87, 0xe1, 0x21, 0xba, 0xac, 0x58, 0x21, 0x16, 0x16, 0x4a, 0x57, 0x6c, 0xfd, 0x00,
	0x08, 0xd9, 0x33, 0x49, 0xdd, 0x26, 0x85, 0x05, 0x3b, 0xfb, 0xdc, 0x73, 0xcf, 0xb9, 0x3a, 0xf7,
	0xda, 0xa0, 0xc2, 0x42, 0x7d, 0x40, 0x91, 0x3e, 0xda, 0xd7, 0x5d, 0xe4, 0x23, 0x8a, 0xa9, 0x36,
	0x08, 0x08, 0x23, 0xf2, 0x2a, 0x0b, 0xb5, 0x01, 0x45, 0xda, 0x68, 0x7f, 0x67, 0xdb, 0x26, 0xd4,
	0x23, 0xd4, 0x4a, 0x0b, 0x3a, 0x7f, 0xe1, 0xac, 0x9d, 0x2d, 0x97, 0xb8, 0x84, 0xe3, 0xc9, 0x93,
	0x40, 0x77, 0xaf, 0x44, 0x1d, 0x4c, 0x59, 0x80, 0xbb, 0x43, 0x86, 0x89, 0x2f, 0xaa, 0xe5, 0xab,
	0xea, 0x00, 0x06, 0xd0, 0x13, 0x5a, 0xea, 0x87, 0x02, 0x58, 0x3f, 0xe6, 0x33, 0x74, 0x18, 0x64,
	0x48, 0xd6, 0xc1, 0x0a, 0x27, 0x54, 0xa5, 0xba, 0xd4, 0x58, 0x3b, 0xd8, 0xd4, 0x66, 0x33, 0x69,
	0x2f, 0xd3, 0x82, 0x51, 0x38, 0x8f, 0x94, 0x9c, 0x29, 0x68, 0xf2, 0x7b, 0x09, 0x54, 0xa8, 0xdd,
	0x43, 0xce, 0xb0, 0x8f, 0x1c, 0x2b, 0x6b, 0x4d, 0xab, 0x4b, 0xf5, 0x7c, 0x63, 0xed, 0xa0, 0x9e,
	0x91, 0xe8, 0x4c, 0x99, 0xad, 0x0c, 0xd1, 0xb8, 0x9f, 0x28, 0xc6, 0x91, 0x52, 0x1b, 0x43, 0xaf,
	0xff, 0x54, 0xbd, 0x45, 0x4e, 0x35, 0xcb, 0x74, 0x51, 0x3b, 0x95, 0x3f, 0x4a, 0xa0, 0xe2, 0xa0,
	0x3e, 0x72, 0x61, 0xf2, 0x6e, 0x31, 0xec, 0x21, 0x0b, 0xf9, 0x2c, 0xc0, 0x88, 0x56, 0xf3, 0xe9,
	0x0c, 0xf7, 0x32, 0x33, 0xb4, 0x66, 0xcc, 0xd7, 0xd8, 0x43, 0x47, 0x3e, 0x0b, 0xc6, 0x47, 0xe1,
	0x80, 0x04, 0xec, 0xe6, 0x1c, 0xb7, 0x48, 0xaa, 0x66, 0xc9, 0x99, 0x93, 0xc0, 0x88, 0xca, 0x6f,
	0x41, 0x11, 0xda, 0x36, 0x19, 0xfa, 0xcc, 0xa2, 0x36, 0x09, 0x10, 0xad, 0x16, 0x52, 0xf3, 0x4a,
	0xc6, 0xfc, 0x90, 0x13, 0x3a, 0x49, 0xdd, 0xd8, 0x13, 0x7e, 0x25, 0xee, 0x77, 0xbd, 0x59, 0x35,
	0x37, 0x60, 0x86, 0x4c, 0xe5, 0x37, 0xa0, 0x7c, 0x2d, 0x8f, 0x24, 0x1d, 0xd8, 0xed, 0x23, 0xa7,
	0xba, 0x5c, 0x97, 0x1a, 0xff, 0x1a, 0x77, 0xe3, 0x48, 0xd9, 0x13, 0x93, 0x2f, 0xe4, 0x25, 0x83,
	0x67, 0x0b, 0xad, 0x29, 0xfe, 0x23, 0x0f, 0xb6, 0x6f, 0x4d, 0x45, 0x86, 0x60, 0x73, 0x04, 0xfb,
	0xd8, 0x81, 0x8c, 0x04, 0x16, 0x74, 0x9c, 0x00, 0x51, 0x7e, 0x1d, 0xab, 0xc6, 0xe3, 0x38, 0x52,
	0xaa, 0xdc, 0x72, 0x8e, 0xa2, 0x7e, 0xf9, 0xdc, 0xdc, 0x12, 0x87, 0x7b, 0xc8, 0xa1, 0x0e, 0x0b,
	0xb0, 0xef, 0x9a, 0xff, 0xcf, 0xb8, 0x02, 0x4f, 0x2c, 0x44, 0xa4, 0x19, 0x8b, 0xa5, 0x9b, 0x16,
	0x73, 0x94, 0xdf, 0x58, 0xcc, 0xb8, 0x53, 0x8b, 0x53, 0xb0, 0x42, 0x7b, 0x30, 0x48, 0x2f, 0x22,
	0xd1, 0x35, 0x92, 0xec, 0xbf, 0x45, 0xca, 0x1d, 0xde, 0x4f, 0x9d, 0x33, 0x0d, 0x13, 0xdd, 0x83,
	0xac, 0xa7, 0xbd, 0x40, 0x2e, 0xb4, 0xc7, 0x2d, 0x64, 0xc7, 0x91, 0xb2, 0x21, 0x4e, 0x32, 0x6d,
	0x4d, 0xfc, 0x80, 0xf0, 0x6b, 0x21, 0xdb, 0x14, 0x8a, 0x72, 0x07, 0x94, 0xfa, 0x90, 0x32, 0xcb,
	0xee, 0x41, 0xdf, 0x45, 0x8e, 0x35, 0xf4, 0x71, 0x68, 0x51, 0x64, 0x57, 0x0b, 0x75, 0xa9, 0x91,
	0x37, 0xea, 0x71, 0xa4, 0xec, 0x72, 0x9d, 0x85, 0x34, 0xd5, 0x94, 0x13, 0xfc, 0x39, 0x87, 0x4f,
	0x7c, 0x1c, 0x76, 0x90, 0x2d, 0x9f, 0x80, 0xff, 0xb2, 0xdb, 0xb2, 0x30, 0xdf, 0x73, 0xc1, 0x78,
	0x38, 0x89, 0x94, 0x62, 0xf6, 0x03, 0x68, 0xb7, 0xe2, 0x48, 0x29, 0xcf, 0x6f, 0xde, 0xc2, 0x8e,
	0x6a, 0x16, 0xb3, 0x48, 0xdb, 0x51, 0x7f, 0x4a, 0x60, 0x3d, 0x7b, 0x84, 0x72, 0x0b, 0xfc, 0x73,
	0x7d, 0xa9, 0x0f, 0xe2, 0x48, 0x29, 0x8a, 0x8b, 0xfc, 0x53, 0xce, 0xd3, 0x56, 0xf9, 0x15, 0x58,
	0x4e, 0xcf, 0x56, 0x6c, 0xed, 0x99, 0x48, 0xb7, 0x34, 0x9f, 0x6e, 0xdb, 0x67, 0x71, 0xa4, 0xac,
	0x4f, 0x3f, 0x75, 0x12, 0xa0, 0x6c, 0xac, 0x6d, 0x9f, 0x99, 0x5c, 0x69, 0x51, 0x00, 0xf9, 0xbf,
	0x0f, 0xc0, 0x38, 0x3e, 0x9f, 0xd4, 0xa4, 0x8b, 0x49, 0x4d, 0xfa, 0x3e, 0xa9, 0x49, 0x9f, 0x2e,
	0x6b, 0xb9, 0x8b, 0xcb, 0x5a, 0xee, 0xeb, 0x65, 0x2d, 0x77, 0xda, 0x74, 0x31, 0xeb, 0x0d, 0xbb,
	0x9a, 0x4d, 0x3c, 0x9d, 0x91, 0x33, 0xe4, 0xe3, 0x77, 0xa8, 0x19, 0xea, 0x2c, 0x6c, 0xda, 0x3d,
	0x88, 0x7d, 0x7d, 0xf4, 0x44, 0xe7, 0x7f, 0x51, 0x36, 0x1e, 0x20, 0xda, 0x5d, 0x49, 0x7f, 0xa1,
	0x8f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xee, 0xe1, 0xef, 0x4d, 0xcf, 0x05, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DistributionsDisabled {
		i--
		if m.DistributionsDisabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.AccountScores) > 0 {
		for iNdEx := len(m.AccountScores) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccountScores[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.DelegationTimeEntries) > 0 {
		for iNdEx := len(m.DelegationTimeEntries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DelegationTimeEntries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ScheduledDistributions) > 0 {
		for iNdEx := len(m.ScheduledDistributions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ScheduledDistributions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *DelegationTimeEntryExport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegationTimeEntryExport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegationTimeEntryExport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DistributionID != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DistributionID))
		i--
		dAtA[i] = 0x28
	}
	if m.LastChangedUnixSec != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LastChangedUnixSec))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.Shares.Size()
		i -= size
		if _, err := m.Shares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.DelegatorAddress) > 0 {
		i -= len(m.DelegatorAddress)
		copy(dAtA[i:], m.DelegatorAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.DelegatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AccountScore) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountScore) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountScore) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DistributionID != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DistributionID))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.Score.Size()
		i -= size
		if _, err := m.Score.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.ScheduledDistributions) > 0 {
		for _, e := range m.ScheduledDistributions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DelegationTimeEntries) > 0 {
		for _, e := range m.DelegationTimeEntries {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AccountScores) > 0 {
		for _, e := range m.AccountScores {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.DistributionsDisabled {
		n += 2
	}
	return n
}

func (m *DelegationTimeEntryExport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.DelegatorAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Shares.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.LastChangedUnixSec != 0 {
		n += 1 + sovGenesis(uint64(m.LastChangedUnixSec))
	}
	if m.DistributionID != 0 {
		n += 1 + sovGenesis(uint64(m.DistributionID))
	}
	return n
}

func (m *AccountScore) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Score.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.DistributionID != 0 {
		n += 1 + sovGenesis(uint64(m.DistributionID))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScheduledDistributions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScheduledDistributions = append(m.ScheduledDistributions, ScheduledDistribution{})
			if err := m.ScheduledDistributions[len(m.ScheduledDistributions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationTimeEntries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegationTimeEntries = append(m.DelegationTimeEntries, DelegationTimeEntryExport{})
			if err := m.DelegationTimeEntries[len(m.DelegationTimeEntries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountScores", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountScores = append(m.AccountScores, AccountScore{})
			if err := m.AccountScores[len(m.AccountScores)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionsDisabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DistributionsDisabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DelegationTimeEntryExport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegationTimeEntryExport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegationTimeEntryExport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Shares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastChangedUnixSec", wireType)
			}
			m.LastChangedUnixSec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastChangedUnixSec |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionID", wireType)
			}
			m.DistributionID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistributionID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountScore) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountScore: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountScore: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Score.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionID", wireType)
			}
			m.DistributionID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistributionID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
