// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tx/pse/v1/staking.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DelegationTimeEntry struct {
	// shares define the delegation shares received.
	Shares cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=shares,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"shares"`
	// last block timestamp where the delegators balance changed.
	LastChangedUnixSec int64 `protobuf:"varint,2,opt,name=last_changed_unix_sec,json=lastChangedUnixSec,proto3" json:"last_changed_unix_sec,omitempty"`
}

func (m *DelegationTimeEntry) Reset()         { *m = DelegationTimeEntry{} }
func (m *DelegationTimeEntry) String() string { return proto.CompactTextString(m) }
func (*DelegationTimeEntry) ProtoMessage()    {}
func (*DelegationTimeEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_36586b90c03866cb, []int{0}
}
func (m *DelegationTimeEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegationTimeEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegationTimeEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegationTimeEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegationTimeEntry.Merge(m, src)
}
func (m *DelegationTimeEntry) XXX_Size() int {
	return m.Size()
}
func (m *DelegationTimeEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegationTimeEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DelegationTimeEntry proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DelegationTimeEntry)(nil), "tx.pse.v1.DelegationTimeEntry")
}

func init() { proto.RegisterFile("tx/pse/v1/staking.proto", fileDescriptor_36586b90c03866cb) }

var fileDescriptor_36586b90c03866cb = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x90, 0xb1, 0x4a, 0x33, 0x41,
	0x10, 0xc7, 0x6f, 0xbf, 0x0f, 0x82, 0xb9, 0xf2, 0x54, 0x8c, 0x11, 0xee, 0x82, 0x55, 0x9a, 0xdb,
	0xe5, 0xb0, 0x11, 0xcb, 0x18, 0x11, 0xc1, 0x2a, 0x6a, 0x63, 0x73, 0x6c, 0x36, 0xc3, 0xde, 0x92,
	0xdc, 0xee, 0x91, 0x9d, 0x84, 0x8d, 0x4f, 0x60, 0xe9, 0x0b, 0x08, 0x79, 0x08, 0x1f, 0x22, 0x65,
	0xb0, 0x12, 0x8b, 0x20, 0x49, 0xe3, 0x63, 0x48, 0xb2, 0xe9, 0x66, 0xfe, 0xbf, 0xe1, 0x37, 0xcc,
	0x84, 0x27, 0xe8, 0x58, 0x65, 0x81, 0x4d, 0x33, 0x66, 0x91, 0x0f, 0x95, 0x96, 0xb4, 0x1a, 0x1b,
	0x34, 0x51, 0x1d, 0x1d, 0xad, 0x2c, 0xd0, 0x69, 0xd6, 0x3c, 0x15, 0xc6, 0x96, 0xc6, 0xe6, 0x3b,
	0xc0, 0x7c, 0xe3, 0xa7, 0x9a, 0x47, 0xd2, 0x48, 0xe3, 0xf3, 0x6d, 0xe5, 0xd3, 0xf3, 0x77, 0x12,
	0x1e, 0x76, 0x61, 0x04, 0x92, 0xa3, 0x32, 0xfa, 0x51, 0x95, 0x70, 0xa3, 0x71, 0x3c, 0x8b, 0xee,
	0xc2, 0x9a, 0x2d, 0xf8, 0x18, 0x6c, 0x83, 0xb4, 0x48, 0xbb, 0xde, 0xc9, 0x16, 0xab, 0x24, 0xf8,
	0x5e, 0x25, 0x67, 0xde, 0x69, 0x07, 0x43, 0xaa, 0x0c, 0x2b, 0x39, 0x16, 0xf4, 0x1e, 0x24, 0x17,
	0xb3, 0x2e, 0x88, 0xcf, 0x8f, 0x34, 0xdc, 0xaf, 0xec, 0x82, 0xe8, 0xed, 0x05, 0x51, 0x16, 0x1e,
	0x8f, 0xb8, 0xc5, 0x5c, 0x14, 0x5c, 0x4b, 0x18, 0xe4, 0x13, 0xad, 0x5c, 0x6e, 0x41, 0x34, 0xfe,
	0xb5, 0x48, 0xfb, 0x7f, 0x2f, 0xda, 0xc2, 0x6b, 0xcf, 0x9e, 0xb4, 0x72, 0x0f, 0x20, 0xae, 0x0e,
	0x5e, 0xe7, 0x49, 0xf0, 0x3b, 0x4f, 0x82, 0xce, 0xed, 0x62, 0x1d, 0x93, 0xe5, 0x3a, 0x26, 0x3f,
	0xeb, 0x98, 0xbc, 0x6d, 0xe2, 0x60, 0xb9, 0x89, 0x83, 0xaf, 0x4d, 0x1c, 0x3c, 0xa7, 0x52, 0x61,
	0x31, 0xe9, 0x53, 0x61, 0x4a, 0x86, 0x66, 0x08, 0x5a, 0xbd, 0x40, 0xea, 0x18, 0xba, 0x54, 0x14,
	0x5c, 0x69, 0x36, 0xbd, 0x64, 0xfe, 0x5f, 0x38, 0xab, 0xc0, 0xf6, 0x6b, 0xbb, 0x7b, 0x2f, 0xfe,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x0a, 0x5a, 0xc1, 0x46, 0x01, 0x00, 0x00,
}

func (m *DelegationTimeEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegationTimeEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegationTimeEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastChangedUnixSec != 0 {
		i = encodeVarintStaking(dAtA, i, uint64(m.LastChangedUnixSec))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.Shares.Size()
		i -= size
		if _, err := m.Shares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintStaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintStaking(dAtA []byte, offset int, v uint64) int {
	offset -= sovStaking(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DelegationTimeEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Shares.Size()
	n += 1 + l + sovStaking(uint64(l))
	if m.LastChangedUnixSec != 0 {
		n += 1 + sovStaking(uint64(m.LastChangedUnixSec))
	}
	return n
}

func sovStaking(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStaking(x uint64) (n int) {
	return sovStaking(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DelegationTimeEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStaking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegationTimeEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegationTimeEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Shares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastChangedUnixSec", wireType)
			}
			m.LastChangedUnixSec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastChangedUnixSec |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStaking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStaking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStaking(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStaking
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStaking
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStaking
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStaking
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStaking
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStaking
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStaking        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStaking          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStaking = fmt.Errorf("proto: unexpected end of group")
)
