// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tx/pse/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateExcludedAddresses struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// addresses_to_add is the list of addresses to add to the excluded addresses list.
	AddressesToAdd []string `protobuf:"bytes,2,rep,name=addresses_to_add,json=addressesToAdd,proto3" json:"addresses_to_add,omitempty" yaml:"addresses_to_add"`
	// addresses_to_remove is the list of addresses to remove from the excluded addresses list.
	AddressesToRemove []string `protobuf:"bytes,3,rep,name=addresses_to_remove,json=addressesToRemove,proto3" json:"addresses_to_remove,omitempty" yaml:"addresses_to_remove"`
}

func (m *MsgUpdateExcludedAddresses) Reset()         { *m = MsgUpdateExcludedAddresses{} }
func (m *MsgUpdateExcludedAddresses) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateExcludedAddresses) ProtoMessage()    {}
func (*MsgUpdateExcludedAddresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fbcd921f59054cd, []int{0}
}
func (m *MsgUpdateExcludedAddresses) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateExcludedAddresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateExcludedAddresses.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateExcludedAddresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateExcludedAddresses.Merge(m, src)
}
func (m *MsgUpdateExcludedAddresses) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateExcludedAddresses) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateExcludedAddresses.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateExcludedAddresses proto.InternalMessageInfo

func (m *MsgUpdateExcludedAddresses) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateExcludedAddresses) GetAddressesToAdd() []string {
	if m != nil {
		return m.AddressesToAdd
	}
	return nil
}

func (m *MsgUpdateExcludedAddresses) GetAddressesToRemove() []string {
	if m != nil {
		return m.AddressesToRemove
	}
	return nil
}

// MsgUpdateClearingAccountMappings is a governance operation to update the clearing account to recipient mappings.
// This replaces all existing mappings with the new ones provided.
// Must include all non-Community clearing accounts (Foundation, Alliance, Partnership, Investors, Team).
// Community clearing account uses score-based distribution and should not have recipient mappings.
type MsgUpdateClearingAccountMappings struct {
	// authority is the address authorized to update mappings (governance module address).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// mappings is the complete list of clearing account to recipient mappings.
	// This replaces all existing mappings. Must include all non-Community clearing accounts.
	Mappings []ClearingAccountMapping `protobuf:"bytes,2,rep,name=mappings,proto3" json:"mappings" yaml:"mappings"`
}

func (m *MsgUpdateClearingAccountMappings) Reset()         { *m = MsgUpdateClearingAccountMappings{} }
func (m *MsgUpdateClearingAccountMappings) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateClearingAccountMappings) ProtoMessage()    {}
func (*MsgUpdateClearingAccountMappings) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fbcd921f59054cd, []int{1}
}
func (m *MsgUpdateClearingAccountMappings) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateClearingAccountMappings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateClearingAccountMappings.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateClearingAccountMappings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateClearingAccountMappings.Merge(m, src)
}
func (m *MsgUpdateClearingAccountMappings) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateClearingAccountMappings) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateClearingAccountMappings.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateClearingAccountMappings proto.InternalMessageInfo

func (m *MsgUpdateClearingAccountMappings) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateClearingAccountMappings) GetMappings() []ClearingAccountMapping {
	if m != nil {
		return m.Mappings
	}
	return nil
}

// MsgUpdateAllocationSchedule is a governance operation to replace the distribution schedule.
// This completely replaces the existing schedule with the new one provided.
// All existing distributions are removed and replaced with the provided schedule.
type MsgUpdateAllocationSchedule struct {
	// authority is the address authorized to update the schedule (governance module address).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// schedule is the complete list of distributions that will replace the existing schedule.
	// All existing distributions are removed and replaced with this schedule.
	Schedule []ScheduledDistribution `protobuf:"bytes,2,rep,name=schedule,proto3" json:"schedule" yaml:"schedule"`
}

func (m *MsgUpdateAllocationSchedule) Reset()         { *m = MsgUpdateAllocationSchedule{} }
func (m *MsgUpdateAllocationSchedule) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateAllocationSchedule) ProtoMessage()    {}
func (*MsgUpdateAllocationSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fbcd921f59054cd, []int{2}
}
func (m *MsgUpdateAllocationSchedule) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateAllocationSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateAllocationSchedule.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateAllocationSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateAllocationSchedule.Merge(m, src)
}
func (m *MsgUpdateAllocationSchedule) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateAllocationSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateAllocationSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateAllocationSchedule proto.InternalMessageInfo

func (m *MsgUpdateAllocationSchedule) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateAllocationSchedule) GetSchedule() []ScheduledDistribution {
	if m != nil {
		return m.Schedule
	}
	return nil
}

type EmptyResponse struct {
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fbcd921f59054cd, []int{3}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return m.Size()
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateExcludedAddresses)(nil), "tx.pse.v1.MsgUpdateExcludedAddresses")
	proto.RegisterType((*MsgUpdateClearingAccountMappings)(nil), "tx.pse.v1.MsgUpdateClearingAccountMappings")
	proto.RegisterType((*MsgUpdateAllocationSchedule)(nil), "tx.pse.v1.MsgUpdateAllocationSchedule")
	proto.RegisterType((*EmptyResponse)(nil), "tx.pse.v1.EmptyResponse")
}

func init() { proto.RegisterFile("tx/pse/v1/tx.proto", fileDescriptor_7fbcd921f59054cd) }

var fileDescriptor_7fbcd921f59054cd = []byte{
	// 572 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4f, 0x8f, 0xd2, 0x40,
	0x18, 0xc6, 0x29, 0x44, 0xb3, 0x8c, 0xd1, 0x75, 0xeb, 0x26, 0xd4, 0xaa, 0x05, 0x1b, 0x35, 0x1b,
	0x0c, 0x34, 0xb0, 0x09, 0x26, 0xdc, 0x40, 0x37, 0x9e, 0xb8, 0xb0, 0xae, 0x87, 0x8d, 0x86, 0x0c,
	0x9d, 0xd9, 0x32, 0xb1, 0xed, 0x34, 0x9d, 0x29, 0x01, 0x4f, 0xc6, 0xa3, 0x27, 0x3f, 0x89, 0xe1,
	0xe0, 0x87, 0xd8, 0x93, 0xd9, 0x78, 0xf2, 0x44, 0x36, 0x70, 0xe0, 0xe0, 0x8d, 0x4f, 0xb0, 0xe9,
	0x1f, 0x0a, 0x2c, 0x74, 0x0f, 0x7b, 0x21, 0x33, 0xbc, 0xcf, 0x3c, 0xbf, 0x3e, 0x6f, 0xdf, 0x0e,
	0x10, 0xf9, 0x40, 0x73, 0x18, 0xd6, 0xfa, 0x15, 0x8d, 0x0f, 0xca, 0x8e, 0x4b, 0x39, 0x15, 0xb3,
	0xfe, 0x8a, 0xe1, 0x72, 0xbf, 0x22, 0xef, 0x41, 0x8b, 0xd8, 0x54, 0x0b, 0x7e, 0xc3, 0xaa, 0xbc,
	0x6f, 0x50, 0x83, 0x06, 0x4b, 0xcd, 0x5f, 0x45, 0xff, 0x3e, 0xd6, 0x29, 0xb3, 0x28, 0xeb, 0x84,
	0x85, 0x70, 0x13, 0x95, 0x72, 0xe1, 0x4e, 0xb3, 0x98, 0xe1, 0x63, 0x2c, 0x66, 0x44, 0x85, 0xa7,
	0x4b, 0x36, 0x22, 0x8c, 0xbb, 0xa4, 0xeb, 0x71, 0x42, 0xed, 0xb0, 0xaa, 0xfe, 0x49, 0x03, 0xb9,
	0xc5, 0x8c, 0x13, 0x07, 0x41, 0x8e, 0x8f, 0x06, 0xba, 0xe9, 0x21, 0x8c, 0x1a, 0x08, 0xb9, 0x98,
	0x31, 0xcc, 0xc4, 0x1a, 0xc8, 0x42, 0x8f, 0xf7, 0xa8, 0x4b, 0xf8, 0x50, 0x12, 0x0a, 0xc2, 0x41,
	0xb6, 0x29, 0xfd, 0xfd, 0x5d, 0xda, 0x8f, 0xd0, 0x91, 0xf0, 0x98, 0xbb, 0xc4, 0x36, 0xda, 0x4b,
	0xa9, 0xf8, 0x19, 0x3c, 0x84, 0x0b, 0x93, 0x0e, 0xa7, 0x1d, 0x88, 0x90, 0x94, 0x2e, 0x64, 0x0e,
	0xb2, 0xcd, 0xc3, 0xf9, 0x38, 0x9f, 0x1b, 0x42, 0xcb, 0xac, 0xab, 0xd7, 0x15, 0x6a, 0xa2, 0xf3,
	0x83, 0x58, 0xfa, 0x81, 0x36, 0x10, 0x12, 0xcf, 0xc0, 0xa3, 0xb5, 0xc3, 0x2e, 0xb6, 0x68, 0x1f,
	0x4b, 0x99, 0x80, 0x50, 0x9b, 0x8f, 0xf3, 0xf2, 0x16, 0x42, 0x28, 0x4a, 0x86, 0xec, 0xad, 0x40,
	0xda, 0x81, 0xb6, 0x5e, 0xf9, 0x3e, 0x1b, 0x15, 0x97, 0xb1, 0x7e, 0xcc, 0x46, 0x45, 0xc5, 0xef,
	0x65, 0x72, 0xc7, 0xd4, 0xff, 0x02, 0x28, 0xc4, 0xe5, 0xb7, 0x26, 0x86, 0xbe, 0x77, 0x43, 0xd7,
	0xa9, 0x67, 0xf3, 0x16, 0x74, 0x1c, 0x62, 0x1b, 0xb7, 0x6f, 0xeb, 0x47, 0xb0, 0x63, 0x45, 0x1e,
	0x41, 0x3b, 0xef, 0x55, 0x9f, 0x97, 0xe3, 0x31, 0x2a, 0x6f, 0xa7, 0x35, 0x73, 0xe7, 0xe3, 0x7c,
	0x6a, 0x3e, 0xce, 0xef, 0x86, 0x3d, 0x59, 0x18, 0xa8, 0xed, 0xd8, 0xab, 0xfe, 0x66, 0x33, 0xe7,
	0x8b, 0xb5, 0x9c, 0x09, 0x41, 0xd4, 0x4b, 0x01, 0x3c, 0x89, 0x45, 0x0d, 0xd3, 0xa4, 0x3a, 0xf4,
	0x87, 0xeb, 0x58, 0xef, 0x61, 0xe4, 0x99, 0xf8, 0xd6, 0x41, 0x4f, 0xc0, 0x0e, 0x8b, 0x3c, 0xa2,
	0xa0, 0x85, 0x95, 0xa0, 0x0b, 0x7b, 0xf4, 0x6e, 0x65, 0xa0, 0xaf, 0xe7, 0x5c, 0x9c, 0x57, 0xdb,
	0xb1, 0x55, 0xbd, 0xba, 0x99, 0x33, 0xbf, 0x96, 0x73, 0x33, 0x82, 0xba, 0x0b, 0xee, 0x1f, 0x59,
	0x0e, 0x1f, 0xb6, 0x31, 0x73, 0xa8, 0xcd, 0x70, 0xf5, 0x57, 0x1a, 0x64, 0x5a, 0xcc, 0x10, 0x4f,
	0x41, 0x2e, 0xe9, 0xb3, 0x79, 0xb9, 0xf2, 0xb0, 0xc9, 0xb3, 0x22, 0x4b, 0x2b, 0xb2, 0x35, 0x86,
	0x78, 0x06, 0x9e, 0xdd, 0x3c, 0x41, 0xaf, 0xb7, 0x11, 0x12, 0xc4, 0x37, 0x70, 0x3e, 0x01, 0x29,
	0xf1, 0xdd, 0xbd, 0xda, 0x86, 0xd8, 0xd4, 0x25, 0xbb, 0xcb, 0x77, 0xbe, 0xcd, 0x46, 0x45, 0xa1,
	0xf9, 0xfe, 0x7c, 0xa2, 0x08, 0x17, 0x13, 0x45, 0xb8, 0x9c, 0x28, 0xc2, 0xcf, 0xa9, 0x92, 0xba,
	0x98, 0x2a, 0xa9, 0x7f, 0x53, 0x25, 0x75, 0x5a, 0x32, 0x08, 0xef, 0x79, 0xdd, 0xb2, 0x4e, 0x2d,
	0x8d, 0xd3, 0x2f, 0xd8, 0x26, 0x5f, 0x71, 0x69, 0xa0, 0xf1, 0x41, 0x49, 0xef, 0x41, 0x62, 0x6b,
	0xfd, 0x9a, 0x16, 0x5e, 0x5e, 0x7c, 0xe8, 0x60, 0xd6, 0xbd, 0x1b, 0xdc, 0x59, 0x87, 0x57, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x7f, 0x34, 0xab, 0xc4, 0x4f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateExcludedAddresses is a governance operation to update the list of excluded addresses.
	UpdateExcludedAddresses(ctx context.Context, in *MsgUpdateExcludedAddresses, opts ...grpc.CallOption) (*EmptyResponse, error)
	// UpdateClearingAccountMappings is a governance operation to update clearing account to recipient mappings.
	UpdateClearingAccountMappings(ctx context.Context, in *MsgUpdateClearingAccountMappings, opts ...grpc.CallOption) (*EmptyResponse, error)
	// UpdateAllocationSchedule is a governance operation to update the distribution schedule.
	UpdateAllocationSchedule(ctx context.Context, in *MsgUpdateAllocationSchedule, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateExcludedAddresses(ctx context.Context, in *MsgUpdateExcludedAddresses, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tx.pse.v1.Msg/UpdateExcludedAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateClearingAccountMappings(ctx context.Context, in *MsgUpdateClearingAccountMappings, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tx.pse.v1.Msg/UpdateClearingAccountMappings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAllocationSchedule(ctx context.Context, in *MsgUpdateAllocationSchedule, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tx.pse.v1.Msg/UpdateAllocationSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateExcludedAddresses is a governance operation to update the list of excluded addresses.
	UpdateExcludedAddresses(context.Context, *MsgUpdateExcludedAddresses) (*EmptyResponse, error)
	// UpdateClearingAccountMappings is a governance operation to update clearing account to recipient mappings.
	UpdateClearingAccountMappings(context.Context, *MsgUpdateClearingAccountMappings) (*EmptyResponse, error)
	// UpdateAllocationSchedule is a governance operation to update the distribution schedule.
	UpdateAllocationSchedule(context.Context, *MsgUpdateAllocationSchedule) (*EmptyResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateExcludedAddresses(ctx context.Context, req *MsgUpdateExcludedAddresses) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExcludedAddresses not implemented")
}
func (*UnimplementedMsgServer) UpdateClearingAccountMappings(ctx context.Context, req *MsgUpdateClearingAccountMappings) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClearingAccountMappings not implemented")
}
func (*UnimplementedMsgServer) UpdateAllocationSchedule(ctx context.Context, req *MsgUpdateAllocationSchedule) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAllocationSchedule not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateExcludedAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateExcludedAddresses)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateExcludedAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tx.pse.v1.Msg/UpdateExcludedAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateExcludedAddresses(ctx, req.(*MsgUpdateExcludedAddresses))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateClearingAccountMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateClearingAccountMappings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateClearingAccountMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tx.pse.v1.Msg/UpdateClearingAccountMappings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateClearingAccountMappings(ctx, req.(*MsgUpdateClearingAccountMappings))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAllocationSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAllocationSchedule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAllocationSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tx.pse.v1.Msg/UpdateAllocationSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAllocationSchedule(ctx, req.(*MsgUpdateAllocationSchedule))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tx.pse.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateExcludedAddresses",
			Handler:    _Msg_UpdateExcludedAddresses_Handler,
		},
		{
			MethodName: "UpdateClearingAccountMappings",
			Handler:    _Msg_UpdateClearingAccountMappings_Handler,
		},
		{
			MethodName: "UpdateAllocationSchedule",
			Handler:    _Msg_UpdateAllocationSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tx/pse/v1/tx.proto",
}

func (m *MsgUpdateExcludedAddresses) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateExcludedAddresses) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateExcludedAddresses) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AddressesToRemove) > 0 {
		for iNdEx := len(m.AddressesToRemove) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AddressesToRemove[iNdEx])
			copy(dAtA[i:], m.AddressesToRemove[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.AddressesToRemove[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.AddressesToAdd) > 0 {
		for iNdEx := len(m.AddressesToAdd) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AddressesToAdd[iNdEx])
			copy(dAtA[i:], m.AddressesToAdd[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.AddressesToAdd[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateClearingAccountMappings) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateClearingAccountMappings) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateClearingAccountMappings) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Mappings) > 0 {
		for iNdEx := len(m.Mappings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Mappings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateAllocationSchedule) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateAllocationSchedule) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateAllocationSchedule) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Schedule) > 0 {
		for iNdEx := len(m.Schedule) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Schedule[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EmptyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmptyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmptyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateExcludedAddresses) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.AddressesToAdd) > 0 {
		for _, s := range m.AddressesToAdd {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.AddressesToRemove) > 0 {
		for _, s := range m.AddressesToRemove {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateClearingAccountMappings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Mappings) > 0 {
		for _, e := range m.Mappings {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateAllocationSchedule) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Schedule) > 0 {
		for _, e := range m.Schedule {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *EmptyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateExcludedAddresses) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateExcludedAddresses: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateExcludedAddresses: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressesToAdd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressesToAdd = append(m.AddressesToAdd, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressesToRemove", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressesToRemove = append(m.AddressesToRemove, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateClearingAccountMappings) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateClearingAccountMappings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateClearingAccountMappings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mappings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mappings = append(m.Mappings, ClearingAccountMapping{})
			if err := m.Mappings[len(m.Mappings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateAllocationSchedule) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateAllocationSchedule: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateAllocationSchedule: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Schedule", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Schedule = append(m.Schedule, ScheduledDistribution{})
			if err := m.Schedule[len(m.Schedule)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmptyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmptyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmptyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
