// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tx/pse/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateExcludedAddresses struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// addresses_to_add is the list of addresses to add to the excluded addresses list.
	AddressesToAdd []string `protobuf:"bytes,2,rep,name=addresses_to_add,json=addressesToAdd,proto3" json:"addresses_to_add,omitempty" yaml:"addresses_to_add"`
	// addresses_to_remove is the list of addresses to remove from the excluded addresses list.
	AddressesToRemove []string `protobuf:"bytes,3,rep,name=addresses_to_remove,json=addressesToRemove,proto3" json:"addresses_to_remove,omitempty" yaml:"addresses_to_remove"`
}

func (m *MsgUpdateExcludedAddresses) Reset()         { *m = MsgUpdateExcludedAddresses{} }
func (m *MsgUpdateExcludedAddresses) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateExcludedAddresses) ProtoMessage()    {}
func (*MsgUpdateExcludedAddresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fbcd921f59054cd, []int{0}
}
func (m *MsgUpdateExcludedAddresses) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateExcludedAddresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateExcludedAddresses.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateExcludedAddresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateExcludedAddresses.Merge(m, src)
}
func (m *MsgUpdateExcludedAddresses) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateExcludedAddresses) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateExcludedAddresses.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateExcludedAddresses proto.InternalMessageInfo

func (m *MsgUpdateExcludedAddresses) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateExcludedAddresses) GetAddressesToAdd() []string {
	if m != nil {
		return m.AddressesToAdd
	}
	return nil
}

func (m *MsgUpdateExcludedAddresses) GetAddressesToRemove() []string {
	if m != nil {
		return m.AddressesToRemove
	}
	return nil
}

type EmptyResponse struct {
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fbcd921f59054cd, []int{1}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return m.Size()
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateExcludedAddresses)(nil), "tx.pse.v1.MsgUpdateExcludedAddresses")
	proto.RegisterType((*EmptyResponse)(nil), "tx.pse.v1.EmptyResponse")
}

func init() { proto.RegisterFile("tx/pse/v1/tx.proto", fileDescriptor_7fbcd921f59054cd) }

var fileDescriptor_7fbcd921f59054cd = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4d, 0xab, 0xda, 0x40,
	0x14, 0x86, 0x8d, 0xd2, 0x42, 0x06, 0xfa, 0x61, 0x2a, 0x98, 0x66, 0x11, 0x25, 0x50, 0x10, 0x21,
	0x19, 0xac, 0xe0, 0xc2, 0x9d, 0x82, 0x74, 0xe5, 0xc6, 0xb6, 0x1b, 0xa1, 0x48, 0xcc, 0x4c, 0x27,
	0xa1, 0x4e, 0x26, 0x64, 0xc6, 0x90, 0x74, 0x55, 0xba, 0xec, 0xaa, 0x3f, 0xc5, 0x45, 0x7f, 0x44,
	0x57, 0x45, 0xba, 0xea, 0x4a, 0x8a, 0x2e, 0xdc, 0xfb, 0x0b, 0x2e, 0xf9, 0xb8, 0x7e, 0x5c, 0x6e,
	0x36, 0xe1, 0x9c, 0xbc, 0x4f, 0xde, 0x97, 0x9c, 0x73, 0x80, 0x22, 0x62, 0x18, 0x70, 0x0c, 0xa3,
	0x1e, 0x14, 0xb1, 0x15, 0x84, 0x4c, 0x30, 0x45, 0x4e, 0x2b, 0x8e, 0xad, 0xa8, 0xa7, 0xd5, 0x6d,
	0xea, 0xf9, 0x0c, 0x66, 0xcf, 0x5c, 0xd5, 0x1a, 0x84, 0x11, 0x96, 0x95, 0x30, 0xad, 0x8a, 0xb7,
	0xaf, 0x1d, 0xc6, 0x29, 0xe3, 0x8b, 0x5c, 0xc8, 0x9b, 0x42, 0x6a, 0xe6, 0x1d, 0xa4, 0x9c, 0xa4,
	0x31, 0x94, 0x93, 0x5c, 0x30, 0xfe, 0x54, 0x81, 0x36, 0xe5, 0xe4, 0x63, 0x80, 0x6c, 0x81, 0x27,
	0xb1, 0xb3, 0x5a, 0x23, 0x8c, 0x46, 0x08, 0x85, 0x98, 0x73, 0xcc, 0x95, 0x01, 0x90, 0xed, 0xb5,
	0x70, 0x59, 0xe8, 0x89, 0x44, 0x95, 0xda, 0x52, 0x47, 0x1e, 0xab, 0x7f, 0x7f, 0x99, 0x8d, 0xc2,
	0xbc, 0x00, 0xdf, 0x8b, 0xd0, 0xf3, 0xc9, 0xec, 0x82, 0x2a, 0x9f, 0xc0, 0x4b, 0xfb, 0xde, 0x64,
	0x21, 0xd8, 0xc2, 0x46, 0x48, 0xad, 0xb6, 0x6b, 0x1d, 0x79, 0xdc, 0x3f, 0xed, 0x5a, 0xcd, 0xc4,
	0xa6, 0xab, 0xa1, 0xf1, 0x90, 0x30, 0x4a, 0x9d, 0x9f, 0x9f, 0xd1, 0x0f, 0x6c, 0x84, 0x90, 0xf2,
	0x19, 0xbc, 0xba, 0xf9, 0x38, 0xc4, 0x94, 0x45, 0x58, 0xad, 0x65, 0x09, 0x83, 0xd3, 0xae, 0xa5,
	0x3d, 0x92, 0x90, 0x43, 0xe5, 0x21, 0xf5, 0xab, 0x90, 0x59, 0xc6, 0x0e, 0x7b, 0xdf, 0x8f, 0x9b,
	0xee, 0xe5, 0xb7, 0x7e, 0x1c, 0x37, 0x5d, 0x3d, 0xdd, 0x54, 0xf9, 0xc4, 0x8c, 0x17, 0xe0, 0xd9,
	0x84, 0x06, 0x22, 0x99, 0x61, 0x1e, 0x30, 0x9f, 0xe3, 0xb7, 0x2e, 0xa8, 0x4d, 0x39, 0x51, 0xe6,
	0xa0, 0x59, 0x36, 0xe4, 0x37, 0xd6, 0x79, 0xd9, 0x56, 0xb9, 0xb3, 0xa6, 0x5e, 0x61, 0x37, 0x11,
	0xda, 0x93, 0x6f, 0xc7, 0x4d, 0x57, 0x1a, 0xbf, 0xfb, 0xbd, 0xd7, 0xa5, 0xed, 0x5e, 0x97, 0xfe,
	0xef, 0x75, 0xe9, 0xe7, 0x41, 0xaf, 0x6c, 0x0f, 0x7a, 0xe5, 0xdf, 0x41, 0xaf, 0xcc, 0x4d, 0xe2,
	0x09, 0x77, 0xbd, 0xb4, 0x1c, 0x46, 0xa1, 0x60, 0x5f, 0xb0, 0xef, 0x7d, 0xc5, 0x66, 0x0c, 0x45,
	0x6c, 0x3a, 0xae, 0xed, 0xf9, 0x30, 0x1a, 0xc0, 0xfc, 0x04, 0x45, 0x12, 0x60, 0xbe, 0x7c, 0x9a,
	0xdd, 0x46, 0xff, 0x2e, 0x00, 0x00, 0xff, 0xff, 0x57, 0xb0, 0x54, 0x0d, 0x99, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateExcludedAddresses is a governance operation to update the list of excluded addresses.
	UpdateExcludedAddresses(ctx context.Context, in *MsgUpdateExcludedAddresses, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateExcludedAddresses(ctx context.Context, in *MsgUpdateExcludedAddresses, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/tx.pse.v1.Msg/UpdateExcludedAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateExcludedAddresses is a governance operation to update the list of excluded addresses.
	UpdateExcludedAddresses(context.Context, *MsgUpdateExcludedAddresses) (*EmptyResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateExcludedAddresses(ctx context.Context, req *MsgUpdateExcludedAddresses) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExcludedAddresses not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateExcludedAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateExcludedAddresses)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateExcludedAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tx.pse.v1.Msg/UpdateExcludedAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateExcludedAddresses(ctx, req.(*MsgUpdateExcludedAddresses))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tx.pse.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateExcludedAddresses",
			Handler:    _Msg_UpdateExcludedAddresses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tx/pse/v1/tx.proto",
}

func (m *MsgUpdateExcludedAddresses) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateExcludedAddresses) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateExcludedAddresses) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AddressesToRemove) > 0 {
		for iNdEx := len(m.AddressesToRemove) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AddressesToRemove[iNdEx])
			copy(dAtA[i:], m.AddressesToRemove[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.AddressesToRemove[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.AddressesToAdd) > 0 {
		for iNdEx := len(m.AddressesToAdd) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AddressesToAdd[iNdEx])
			copy(dAtA[i:], m.AddressesToAdd[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.AddressesToAdd[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EmptyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmptyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EmptyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateExcludedAddresses) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.AddressesToAdd) > 0 {
		for _, s := range m.AddressesToAdd {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.AddressesToRemove) > 0 {
		for _, s := range m.AddressesToRemove {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *EmptyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateExcludedAddresses) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateExcludedAddresses: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateExcludedAddresses: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressesToAdd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressesToAdd = append(m.AddressesToAdd, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressesToRemove", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressesToRemove = append(m.AddressesToRemove, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmptyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmptyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmptyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
