// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: coreum/asset/ft/v1/params.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params store gov manageable parameters.
type Params struct {
	// issue_fee is the fee burnt each time new token is issued.
	IssueFee types.Coin `protobuf:"bytes,1,opt,name=issue_fee,json=issueFee,proto3" json:"issue_fee" yaml:"issue_fee"`
	// token_upgrade_decision_timeout defines the end of the decision period for upgrading the token.
	TokenUpgradeDecisionTimeout time.Time `protobuf:"bytes,2,opt,name=token_upgrade_decision_timeout,json=tokenUpgradeDecisionTimeout,proto3,stdtime" json:"token_upgrade_decision_timeout" yaml:"token_upgrade_decision_timeout"`
	// token_upgrade_grace_period the period after which the token upgrade is executed effectively.
	TokenUpgradeGracePeriod time.Duration `protobuf:"bytes,3,opt,name=token_upgrade_grace_period,json=tokenUpgradeGracePeriod,proto3,stdduration" json:"token_upgrade_grace_period" yaml:"token_upgrade_grace_period"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_b08ee2013666b045, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetIssueFee() types.Coin {
	if m != nil {
		return m.IssueFee
	}
	return types.Coin{}
}

func (m *Params) GetTokenUpgradeDecisionTimeout() time.Time {
	if m != nil {
		return m.TokenUpgradeDecisionTimeout
	}
	return time.Time{}
}

func (m *Params) GetTokenUpgradeGracePeriod() time.Duration {
	if m != nil {
		return m.TokenUpgradeGracePeriod
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "coreum.asset.ft.v1.Params")
}

func init() { proto.RegisterFile("coreum/asset/ft/v1/params.proto", fileDescriptor_b08ee2013666b045) }

var fileDescriptor_b08ee2013666b045 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x31, 0x8b, 0xd4, 0x40,
	0x14, 0xc7, 0x33, 0x27, 0x1c, 0x1a, 0x1b, 0x09, 0x82, 0x31, 0xc2, 0x44, 0x03, 0x82, 0xcd, 0xce,
	0x90, 0xb3, 0x11, 0xcb, 0x78, 0x68, 0x63, 0xb1, 0x1c, 0x67, 0x63, 0x13, 0x26, 0xc9, 0x4b, 0x6e,
	0xf0, 0x92, 0x17, 0x32, 0x93, 0xb0, 0x67, 0x6f, 0xbf, 0x58, 0xf9, 0x91, 0xb6, 0xdc, 0xd2, 0x6a,
	0x95, 0xdd, 0x6f, 0x60, 0x63, 0x2b, 0x99, 0xc9, 0xea, 0xba, 0x88, 0xdd, 0x4b, 0xde, 0xef, 0xff,
	0xde, 0x6f, 0x86, 0x71, 0xc3, 0x1c, 0x3b, 0xe8, 0x6b, 0x2e, 0x94, 0x02, 0xcd, 0x4b, 0xcd, 0x87,
	0x98, 0xb7, 0xa2, 0x13, 0xb5, 0x62, 0x6d, 0x87, 0x1a, 0x3d, 0xcf, 0x02, 0xcc, 0x00, 0xac, 0xd4,
	0x6c, 0x88, 0x03, 0x9a, 0xa3, 0xaa, 0x51, 0xf1, 0x4c, 0x28, 0xe0, 0x43, 0x9c, 0x81, 0x16, 0x31,
	0xcf, 0x51, 0x36, 0x36, 0x13, 0xdc, 0xaf, 0xb0, 0x42, 0x53, 0xf2, 0xb1, 0x9a, 0xfe, 0xd2, 0x0a,
	0xb1, 0xba, 0x06, 0x6e, 0xbe, 0xb2, 0xbe, 0xe4, 0x45, 0xdf, 0x09, 0x2d, 0x71, 0x9f, 0x0a, 0x8f,
	0xfb, 0x5a, 0xd6, 0xa0, 0xb4, 0xa8, 0x5b, 0x0b, 0x44, 0x3f, 0x4f, 0xdc, 0xd3, 0xb9, 0x71, 0xf3,
	0xe6, 0xee, 0x1d, 0xa9, 0x54, 0x0f, 0x69, 0x09, 0xe0, 0x93, 0xc7, 0xe4, 0xd9, 0xdd, 0xb3, 0x87,
	0xcc, 0x5a, 0xb1, 0xd1, 0x8a, 0x4d, 0x56, 0xec, 0x15, 0xca, 0x26, 0xf1, 0x57, 0x9b, 0xd0, 0xf9,
	0xb1, 0x09, 0xef, 0xdd, 0x88, 0xfa, 0xfa, 0x65, 0xf4, 0x3b, 0x19, 0x5d, 0xdc, 0x36, 0xf5, 0x6b,
	0x00, 0xef, 0x33, 0x71, 0xa9, 0xc6, 0x0f, 0xd0, 0xa4, 0x7d, 0x5b, 0x75, 0xa2, 0x80, 0xb4, 0x80,
	0x5c, 0x2a, 0x89, 0x4d, 0x3a, 0x7a, 0x60, 0xaf, 0xfd, 0x13, 0xb3, 0x27, 0x60, 0xd6, 0x93, 0xed,
	0x3d, 0xd9, 0xe5, 0xde, 0x33, 0x89, 0xa7, 0x45, 0x4f, 0xed, 0xa2, 0xff, 0xcf, 0x8b, 0x96, 0xdf,
	0x42, 0x72, 0xf1, 0xc8, 0x40, 0xef, 0x2c, 0x73, 0x3e, 0x21, 0x97, 0x96, 0xf0, 0x3e, 0x11, 0x37,
	0xf8, 0x7b, 0x48, 0xd5, 0x89, 0x1c, 0xd2, 0x16, 0x3a, 0x89, 0x85, 0x7f, 0x6b, 0x3a, 0xf8, 0xb1,
	0xd0, 0xf9, 0x74, 0xb1, 0xc9, 0x6c, 0xf2, 0x79, 0xf2, 0x2f, 0x9f, 0xc3, 0x51, 0xd1, 0x97, 0xd1,
	0xe5, 0xc1, 0xa1, 0xcb, 0x9b, 0xb1, 0x3d, 0x37, 0xdd, 0xe4, 0xed, 0x6a, 0x4b, 0xc9, 0x7a, 0x4b,
	0xc9, 0xf7, 0x2d, 0x25, 0xcb, 0x1d, 0x75, 0xd6, 0x3b, 0xea, 0x7c, 0xdd, 0x51, 0xe7, 0xfd, 0x59,
	0x25, 0xf5, 0x55, 0x9f, 0xb1, 0x1c, 0x6b, 0x6e, 0xd2, 0xf2, 0x23, 0xcc, 0x16, 0x5c, 0x2f, 0x66,
	0xf9, 0x95, 0x90, 0x0d, 0x1f, 0x5e, 0xf0, 0xc5, 0x9f, 0xc7, 0xa5, 0x6f, 0x5a, 0x50, 0xd9, 0xa9,
	0x11, 0x7d, 0xfe, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x15, 0xfe, 0x0f, 0x7c, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.TokenUpgradeGracePeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TokenUpgradeGracePeriod):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1a
	n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.TokenUpgradeDecisionTimeout, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.TokenUpgradeDecisionTimeout):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	{
		size, err := m.IssueFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.IssueFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.TokenUpgradeDecisionTimeout)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TokenUpgradeGracePeriod)
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssueFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IssueFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenUpgradeDecisionTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.TokenUpgradeDecisionTimeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenUpgradeGracePeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.TokenUpgradeGracePeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
