[package]
name = "ibc-callbacks-sender"
description = "Sends a configured coin from an IBC source callback, for testing asset-ft controls"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema.workspace = true
cosmwasm-std.workspace = true
cw-storage-plus.workspace = true
serde.workspace = true
